HazarSchool/Controllers/CourseController.cs
using HazarSchool.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using static HazarSchool.ViewModels.RequestModels.CourseRequestModel;

namespace HazarSchool.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public IActionResult Index()
        {
            var courses = _courseService.GetAllCourses();
            return View(courses);
        }

        public IActionResult CreateCourse()
        {
            return View();
        }

        [HttpPost]

        public IActionResult CreateCourse(CreateCourseRequestModel model)
        {
            _courseService.AddCourse(model);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var course = _courseService.GetCourseById(id);
            return View(course);
        }

        [HttpPost]
        public IActionResult Update(int id, UpdateCourseRequestModel model)
        {
            var course = _courseService.UpdateCourse(id, model);
            {
                return RedirectToAction("Index");
            }
        }
        public IActionResult CourseDetails(int id)
        {
            var course = _courseService.GetCourseById(id);
            return View(course);
        }
        public IActionResult Delete(int id)
        {
            var course = _courseService.GetCourseById(id);
            return View(course);
        }

        [HttpPost, ActionName("Delete")]

        public IActionResult DeleteConfirmed(int id)
        {
            var course = _courseService.DeleteCourse(id);
            return RedirectToAction("index");
        }

    }
}

HazarSchool/Controllers/DepartmentController.cs
using HazarSchool.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using static HazarSchool.ViewModels.RequestModels.DepartmentRequestModel;

namespace HazarSchool.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;
        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public IActionResult Index()
        {
            var departments = _departmentService.GetAllDepartments();
            return View(departments);
        }

        public IActionResult AddDepartment()
        {
            return View();
        }

        [HttpPost]

        public IActionResult AddDepartment(CreateDepartmentRequestModel model)
        {
            var response = _departmentService.AddDepartment(model);
            if (!response.Status)
            {
                ViewBag["Department enter Already exist"] = response.Message;
            }
            return RedirectToAction("Index");
        }

        public IActionResult UpdateDepartment(int id)
        {
            var department = _departmentService.GetDepartmentById(id);
            return View(department.Data);
        }

        [HttpPost]

        public IActionResult UpdateDepartment(int id, UpdateDepartmentRequestModel model)
        {
            _departmentService.UpdateDepartment(id, model);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var department = _departmentService.GetDepartmentById(id);
            return View(department);
        }
        
        public IActionResult Delete(int id)
        {
            var department = _departmentService.GetDepartmentById(id);
            return View(department);
        }

        [HttpPost, ActionName("Delete")]

        public IActionResult DeleteConfirmed(int id)
        {
            var department = _departmentService.DeleteDepartment(id);
            return RedirectToAction("Index");
        }
    }
}

HazarSchool/Controllers/StudentController.cs
using HazarSchool.Interfaces.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Security.Claims;
using static HazarSchool.ViewModels.RequestModels.StudentRequestModel;

namespace HazarSchool.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly IDepartmentService _departmentService;
        private readonly ICourseService _courseService;
        public StudentController(IStudentService studentService, IDepartmentService department, ICourseService courseService)

        {
            _studentService = studentService;
            _departmentService = department;
            _courseService = courseService;
        }

        public IActionResult Index()
        {
            if(ModelState.IsValid)
            {

            }
            var students = _studentService.GetAllStudents();
            return View(students);
        }

        public IActionResult FemaleStudents()
        {
            var femaleStudents = _studentService.GetFemaleStudents();
            return View(femaleStudents);
        }

        public IActionResult MaleStudents()
        {
            var maleStudents = _studentService.GetMaleStudents();
            return View(maleStudents);
        }
        public IActionResult AddStudent()
        {
            var departments = _departmentService.GetAllDepartments();
            var courses = _courseService.GetAllCourses();
            ViewData["Departments"] = new SelectList(departments.Data, "Id", "Name");
            ViewData["Courses"] = new SelectList(courses.Data, "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(CreateStudentRequestModel model)
        {
            _studentService.AddStudent(model);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var student = _studentService.FindStudentByid(id);
            return View(student.Data);
        }

        [HttpPost]
        public IActionResult Update(int id, UpdateStudentRequestModel model)
        {
            _studentService.UpdateStudent(id, model);
            return RedirectToAction("index");
        }

        public IActionResult UpdateProfile()
        {
            int id = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var student = _studentService.FindStudentByid(id);
            return View(student.Data);
        }

        [HttpPost]
        public IActionResult UpdateProfile(UpdateStudentRequestModel model)
        {
            int id = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
             _studentService.UpdateStudent(id, model);
            var student = _studentService.FindStudentByid(id);
            return RedirectToAction("StudentDetails", student.Data);
        }
        public IActionResult StudentDetails(int id)
        {
            var student = _studentService.FindStudentByid(id);
            return View(student);
        }

        [Authorize]
        public IActionResult DeleteStudent(int id)
        {
            var student = _studentService.FindStudentByid(id);
            return View(student);
        }

        [Authorize]
        [HttpPost, ActionName("DeleteStudent")]
        public IActionResult DeleteConfirmed(int id)
        {
            var student = _studentService.DeleteStudent(id);
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]

        public IActionResult Login(StudentLoginRequestModel model)
        {
            var loginStatus = _studentService.Login(model);
            if (loginStatus.Status == false)
            {
                ViewBag.Message = loginStatus.Message;
                return View();
            }
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, loginStatus.Data.FirstName),
                new Claim(ClaimTypes.NameIdentifier, loginStatus.Data.Id.ToString()),
                new Claim(ClaimTypes.GivenName, $"{loginStatus.Data.FirstName} {loginStatus.Data.LastName}"),
                new Claim(ClaimTypes.Email, loginStatus.Data.Email)
            };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authenticationProperties = new AuthenticationProperties();
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, authenticationProperties);
            return RedirectToAction("StudentDetails", loginStatus.Data);
        }
        public IActionResult LogOut()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }


        /*public IActionResult Login(StudentLoginRequestModel model)
        {
           var loginStatus = _studentService.Login(model);
            if (loginStatus.Status == false)
            {
                ViewBag.Message = loginStatus.Message;
                return View();
            }
            if (loginStatus.Status == true)
            {
                ViewBag.Message = loginStatus.Message;
                return RedirectToAction("Index");
            }
            HttpContext.Session.SetInt32("Id", loginStatus.Data.Id);
            HttpContext.Session.SetString("Email", loginStatus.Data.Email);
            return RedirectToAction("Index");
        }*/

        /*public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }*/
    }
}

HazarSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hazar School</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HazarSchool </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                   
                    @if(User.Identity.IsAuthenticated)
                        {
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="LogOut">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Login">Login</a>
                        </li>
                        }
                     </ul>
                     @if(User.Identity.IsAuthenticated)
                    {
                        <li> @User.Identity.Name</li>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MySchoolApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HazarSchool/Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hazar School</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MySchoolApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="UpdateProfile">Update</a>
                        </li>
                       
                        
                        @if(User.Identity.IsAuthenticated)
                        {
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="LogOut">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Login">Login</a>
                        </li>
                        }

                     </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MySchoolApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>